Repository neetozone/neeto-editor, pull requests merged in 2022-09, with the labels that each got.

#331 Removed Tiptap warnings in console
  lib/components/Editor/CustomExtensions/KeyboardShortcuts/ExtensionConfig.js
  lib/components/Editor/CustomExtensions/SlashCommands/ExtensionConfig.js
  lib/components/Editor/CustomExtensions/useCustomExtensions.js
  package.json
  yarn.lock
Labels: patch

#327 Upload images via a pre-signed URL
  README.md
  lib/components/Editor/CustomExtensions/Image/ExtensionConfig.js
  lib/components/Editor/CustomExtensions/Image/LocalUploader.jsx
  lib/components/Editor/CustomExtensions/Image/constants.js
  lib/components/Editor/index.jsx
  lib/constants/common.js
  lib/utils/ActiveStorageUpload.js
  package.json
  stories/API-Reference/constants.js
  stories/Getting-started.stories.mdx
  yarn.lock
Labels: minor

#338 Prevented direct DOM manipulation in EditorContent component
  README.md
  lib/components/Editor/EditorContent.jsx
  lib/constants/common.js
  lib/utils/highlightCode.js
  package.json
  stories/Getting-started.stories.mdx
  yarn.lock
Labels: patch

#339 Fixed the behaviour of inline code blocks
  lib/components/Editor/CustomExtensions/useCustomExtensions.js
  package.json
  yarn.lock
Labels: patch

#342 Replaced special HTML character entities with the associated character
  lib/utils/highlightCode.js
Labels: patch

#346 Update CHANGELOG.md
  CHANGELOG.md
Labels: patch

#344 Added highlighting to nodes when applying styles
  lib/components/Common/MenuButton.jsx
  lib/components/Editor/CustomExtensions/FixedMenu/constants.js
  lib/components/Editor/CustomExtensions/FixedMenu/index.jsx
  lib/components/Editor/CustomExtensions/FixedMenu/utils.js
  lib/components/Editor/CustomExtensions/SlashCommands/ExtensionConfig.js
  lib/components/Editor/CustomExtensions/useCustomExtensions.js
  lib/styles/editor/_editor-content.scss
  lib/styles/editor/_editor.scss
  lib/utils/focusProps.js
  package.json
  yarn.lock
Labels: patch

#352 Updated the `setMention` command to accept both label and id
  dist/editor-content.min.css
  lib/components/Editor/CustomExtensions/Mention/ExtensionConfig.js
  lib/components/Editor/CustomExtensions/Mention/helpers.js
  lib/components/Editor/CustomExtensions/Mention/index.jsx
  lib/components/Editor/CustomExtensions/useCustomExtensions.js
Labels: patch

#360 Updated URLs in changelog
  CHANGELOG.md
Labels: patch

#362 Clean up CHANGELOG.md file
  CHANGELOG.md
Labels: skip-ci

#363 Added font style dropdown to bubble menu
  lib/components/Editor/CustomExtensions/BubbleMenu/TextOptions.jsx
  lib/components/Editor/CustomExtensions/BubbleMenu/helpers.js
  lib/components/Editor/CustomExtensions/FixedMenu/FontSizeOption.jsx
  lib/components/Editor/CustomExtensions/FixedMenu/index.jsx
  lib/constants/common.js
  lib/styles/editor/_menu.scss
Labels: patch

#366 Fixed issue with autoFocus prop in conditionally rendered editor
  lib/components/Editor/index.jsx
Labels: patch

#368 Added type='submit' to BubbleMenu buttons
  lib/components/Editor/CustomExtensions/BubbleMenu/TextOptions.jsx
Labels: patch

#372 Used v2 of changelog-updater-action
  .github/workflows/publish.yml
  CHANGELOG.md
Labels: patch

#364 Updated the UI to the new design system
  dist/editor-content.min.css
  lib/components/Common/Avatar.jsx
  lib/components/Common/Backdrop.jsx
  lib/components/Common/Button.jsx
  lib/components/Common/Dropdown.jsx
  lib/components/Common/Dropdown/Divider.js
  lib/components/Common/Dropdown/Menu.js
  lib/components/Common/Dropdown/MenuItem/MenuItem.js
  lib/components/Common/Dropdown/MenuItem/MenuItemButton.js
  lib/components/Common/Dropdown/MenuItem/index.js
  lib/components/Common/Dropdown/index.js
  lib/components/Common/Input.jsx
  lib/components/Common/Label.jsx
  lib/components/Common/MenuButton.jsx
  lib/components/Common/Modal.jsx
  lib/components/Common/ModalManager.jsx
  lib/components/Common/Portal.jsx
  lib/components/Common/Tab.jsx
  lib/components/Common/Tab/Item.js
  lib/components/Common/Tab/index.js
  lib/components/Common/constants.js
  lib/components/Editor/CustomExtensions/BubbleMenu/TextOptions.jsx
  lib/components/Editor/CustomExtensions/BubbleMenu/index.jsx
  lib/components/Editor/CustomExtensions/FixedMenu/EmojiOption.jsx
  lib/components/Editor/CustomExtensions/FixedMenu/FontSizeOption.jsx
  lib/components/Editor/CustomExtensions/Image/ImageEditor.jsx
  lib/components/Editor/CustomExtensions/Image/URLForm.jsx
  lib/components/Editor/CustomExtensions/Mention/index.jsx
  lib/components/Editor/CustomExtensions/SlashCommands/ExtensionConfig.js
  lib/components/Editor/CustomExtensions/Variable/index.jsx
  lib/hooks/useModal.jsx
  lib/index.scss
  lib/styles/abstracts/_base.scss
  lib/styles/abstracts/_mixins.scss
  lib/styles/abstracts/_neeto-ui-variables.scss
  lib/styles/abstracts/_normalize.scss
  lib/styles/abstracts/_root.scss
  lib/styles/abstracts/_theme.scss
  lib/styles/components/_avatar.scss
  lib/styles/components/_button.scss
  lib/styles/components/_dropdown.scss
  lib/styles/components/_input.scss
  lib/styles/components/_loader.scss
  lib/styles/components/_modal.scss
  lib/styles/components/_tab.scss
  lib/styles/components/_tooltip.scss
  lib/styles/editor/_commands.scss
  lib/styles/editor/_editor-content.scss
  lib/styles/editor/_editor.scss
  lib/styles/editor/_emoji.scss
  lib/styles/editor/_image-editor.scss
  lib/styles/editor/_image-uploader.scss
  lib/styles/editor/_menu.scss
  lib/utils/common.js
  package.json
  rollup.config.js
  yarn.lock
Labels: minor

#373 Exposed code block highlight feature to CDN
  .gitignore
  dist/codeBlockHighlight.js
  lib/utils/codeBlockHighlight.js
  rollup.config.js
  stories/Walkthroughs/Output.stories.mdx
Labels: minor

#375 Removed the involvement of `@rails/activestorage` in image upload logic
  README.md
  lib/apis/directUploads.js
  lib/components/Editor/CustomExtensions/Image/ExtensionConfig.js
  lib/constants/common.js
  lib/utils/ActiveStorageUpload.js
  lib/utils/DirectUpload/index.js
  lib/utils/DirectUpload/utils.js
  package.json
  stories/API-Reference/constants.js
  stories/Examples/Customize-options/Addons.stories.mdx
  stories/Getting-started.stories.mdx
  yarn.lock
Labels: minor

#377 Fixed overflow in Bubble Menu
  dist/editor-content.min.css
  lib/components/Editor/CustomExtensions/BubbleMenu/index.jsx
  package.json
  rollup.config.js
  yarn.lock
Labels: patch

#380 Fixed: nullish coalescing operator not transpiling
  package.json
  rollup.config.js
  yarn.lock
Labels: patch
