Repository neetozone/neeto-editor, pull requests merged in 2022-12, with the labels that each got.

#481 Removed wrapper div from images
  lib/components/Editor/CustomExtensions/Image/ExtensionConfig.js
  lib/styles/editor/_editor-content.scss
Labels: patch

#484 Removed useEditorStore hook and editorKey prop
  lib/components/Editor/index.jsx
  lib/index.js
  lib/stores/useEditorStore.js
  package.json
  stories/API-Reference/constants.js
  stories/Examples/Independant-menu-component.stories.mdx
  stories/Examples/IndependantMenuComponentDemo.jsx
  stories/Walkthroughs/Editor-instance.stories.mdx
  types.d.ts
  yarn.lock
Labels: minor

#487 Fixed left alignment of figure captions
  lib/styles/editor/_editor-content.scss
Labels: patch

#488 Added ability to add additional menu items through addonCommands prop
  lib/components/Common/MenuButton.jsx
  lib/components/Editor/CustomExtensions/FixedMenu/index.jsx
  lib/components/Editor/CustomExtensions/FixedMenu/utils.jsx
  lib/components/Editor/Menu/index.jsx
  lib/components/Editor/index.jsx
  types.d.ts
Labels: minor

#490 Trimed editor content before testing for emptiness
  lib/utils/common.js
Labels: patch

#496 Added Headless menu type
  lib/components/Common/ToolTip.jsx
  lib/components/Editor/Menu/Bubble/LinkOption.jsx
  lib/components/Editor/Menu/Bubble/Options.jsx
  lib/components/Editor/Menu/Bubble/index.jsx
  lib/components/Editor/Menu/Bubble/utils.jsx
  lib/components/Editor/Menu/Fixed/EmojiOption.jsx
  lib/components/Editor/Menu/Fixed/FontSizeOption.jsx
  lib/components/Editor/Menu/Fixed/LinkOption.jsx
  lib/components/Editor/Menu/Fixed/Separator.jsx
  lib/components/Editor/Menu/Fixed/TextColorOption.jsx
  lib/components/Editor/Menu/Fixed/constants.js
  lib/components/Editor/Menu/Fixed/index.jsx
  lib/components/Editor/Menu/Fixed/utils.jsx
  lib/components/Editor/Menu/Headless/Option/Emoji.jsx
  lib/components/Editor/Menu/Headless/Option/UI/Button.jsx
  lib/components/Editor/Menu/Headless/Option/UI/Dropdown.jsx
  lib/components/Editor/Menu/Headless/Option/index.jsx
  lib/components/Editor/Menu/Headless/constants.js
  lib/components/Editor/Menu/Headless/index.jsx
  lib/components/Editor/Menu/Headless/utils.js
  lib/components/Editor/Menu/index.jsx
  package.json
  stories/Examples/Independant-menu-component.stories.mdx
  stories/Walkthroughs/Menu-types/HeadlessMenu.stories.mdx
  types.d.ts
  yarn.lock
Labels: minor

#504 Failing action will not abort publish
  .github/workflows/publish.yml
Labels: skip-ci

#505 Prevented secondary click for fixed menu buttons
  lib/components/Editor/CustomExtensions/Image/Menu.jsx
  lib/components/Editor/CustomExtensions/Mention/index.jsx
  lib/components/Editor/CustomExtensions/Variable/index.jsx
  lib/components/Editor/Menu/Bubble/LinkOption.jsx
  lib/components/Editor/Menu/Fixed/EmojiOption.jsx
  lib/components/Editor/Menu/Fixed/LinkOption.jsx
  lib/components/Editor/Menu/Fixed/utils.jsx
  lib/styles/editor/_menu.scss
Labels: patch

#507 Add fuzzy search for mentions
  lib/components/Editor/CustomExtensions/Mention/utils.js
  package.json
  yarn.lock
Labels: patch

#506 File attachment component with individual progress
  lib/apis/direct_uploads.js
  lib/components/Attachments/Attachment.jsx
  lib/components/Attachments/AttachmentProgress.jsx
  lib/components/Attachments/constants.js
  lib/components/Attachments/index.jsx
  lib/components/Editor/MediaUploader/LocalUploader.jsx
  lib/hooks/useUppyUploader.js
  lib/index.js
  lib/index.scss
  lib/styles/components/_attachments.scss
  package.json
  yarn.lock
Labels: minor

#509 Scrollbar for menu options
  lib/styles/editor/_menu.scss
Labels: patch

#510 Changed styling of code-block in editor
  lib/styles/editor/_editor-content.scss
Labels: patch

#511 Limit image file size while copying into editor
  lib/components/Editor/CustomExtensions/Image/ExtensionConfig.js
  lib/components/Editor/MediaUploader/constants.js
Labels: patch
