Repository neetozone/neeto-editor, pull requests merged in 2023-03, with the labels that each got.

#646 Menu dropdown shows table options when table is active
  src/components/Editor/CustomExtensions/Table/ExtensionConfig.js
  src/components/Editor/CustomExtensions/Table/TableView.js
  src/components/Editor/CustomExtensions/useCustomExtensions.js
  src/components/Editor/Menu/Bubble/TableOption.jsx
  src/components/Editor/Menu/Fixed/TableActions.jsx
  src/components/Editor/Menu/Fixed/constants.js
  src/components/Editor/Menu/Fixed/index.jsx
  src/components/Editor/Menu/index.jsx
  src/components/Editor/index.jsx
  src/styles/editor/_menu.scss
  src/translations/en.json
  stories/constants.js
Labels: minor

#657 Nanos standardization
  .eslint-rules/custom.js
  .eslint-rules/globals.js
  .eslint-rules/helpers/index.js
  .eslint-rules/imports/enforced.js
  .eslint-rules/imports/order.js
  .eslint-rules/neeto.js
  .eslint-rules/overrides.js
  .eslint-rules/promise.js
  .eslint-rules/react.js
  .eslintignore
  .eslintrc.js
  .github/pull_request_template.md
  .github/release-drafter.yml
  .github/workflows/auto_update_prs_with_latest_main.yml
  .github/workflows/create_and_publish_releases.yml
  .github/workflows/publish.yml
  .prettierrc.js
  .storybook/main.js
  .storybook/preview-head.html
  .storybook/style.scss
  README.md
  alias.js
  babel.config.js
  dist/codeBlockHighlight.js
  dist/editor-content.min.css
  jsconfig.json
  package.json
  postcss.config.js
  resolve.js
  rollup.config.js
  src/apis/direct_uploads.js
  src/apis/emoji_picker.js
  src/apis/unsplash.js
  src/components/Attachments/Attachment.jsx
  src/components/Attachments/index.jsx
  src/components/Editor/CustomExtensions/Embeds/index.jsx
  src/components/Editor/CustomExtensions/Emoji/EmojiSuggestion/EmojiSuggestionMenu.jsx
  src/components/Editor/CustomExtensions/Image/Menu.jsx
  src/components/Editor/CustomExtensions/SlashCommands/constants.js
  src/components/Editor/FormikEditor.jsx
  src/components/Editor/MediaUploader/MediaEditor.jsx
  src/components/Editor/Menu/Bubble/Options.jsx
  src/components/Editor/Menu/Fixed/LinkOption.jsx
  src/components/Editor/Menu/Fixed/constants.js
  src/components/Editor/Menu/Fixed/index.jsx
  src/components/Editor/Menu/Headless/Option/UI/Button.jsx
  src/components/Editor/Menu/Headless/Option/UI/Dropdown.jsx
  src/components/Editor/Menu/Headless/constants.js
  src/components/Editor/index.jsx
  src/components/Editor/utils.js
  src/components/EditorContent/utils.js
  src/hooks/useUppyUploader.js
  src/translations/en.json
  src/utils/DirectUpload/index.js
  src/utils/common.js
  tailwind.config.js
  yarn.lock
Labels: skip-ci

#654 Updated styles to match changes in neetoUi
  dist/editor-content.min.css
  src/styles/components/_attachments.scss
  src/styles/editor/_editor.scss
  src/styles/editor/_emoji.scss
  src/styles/editor/_media-uploader.scss
  src/styles/editor/_menu.scss
  src/styles/editor/_table.scss
Labels: patch

#665 Added data-cy prop for `Attachments` and `Embeds`
  .github/pull_request_template.md
  .node-version
  .nvmrc
  package.json
  src/components/Attachments/Attachment.jsx
  src/components/Attachments/AttachmentProgress.jsx
  src/components/Attachments/index.jsx
  src/components/Editor/CustomExtensions/Embeds/index.jsx
  src/components/Editor/MediaUploader/MediaEditor.jsx
  src/components/Editor/MediaUploader/UnsplashImagePicker.jsx
  src/components/Editor/MediaUploader/index.jsx
  src/components/Editor/Menu/Bubble/LinkOption.jsx
  src/translations/en.json
  yarn.lock
Labels: patch

#664 Removed lodash and replaced with ramda functions
  package.json
  src/components/Editor/CustomExtensions/SlashCommands/ExtensionConfig.js
  src/components/Editor/CustomExtensions/Variable/utils.js
  yarn.lock
Labels: patch

#663 Added documentation for table-addon
  stories/Examples/Table.stories.mdx
Labels: minor

#667 Updated node version
  package.json
Labels: patch

#668 Added esm and cjs bundles
  .gitignore
  package.json
  rollup.config.js
Labels: patch

#670 Removed .npmignore
  .npmignore
Labels: patch

#673 Enabled support for children above EditorContent
  src/components/Editor/index.jsx
  types.d.ts
Labels: minor

#676 Added preview to font size options
  src/components/Editor/Menu/Fixed/FontSizeOption.jsx
  src/components/Editor/Menu/Fixed/constants.js
  src/styles/editor/_editor-content.scss
Labels: patch

#677 Removed changelog stories and updated engines
  .storybook/preview.js
  CHANGELOG.md
  package.json
  stories/Changelog.stories.mdx
Labels: patch

#675 Removed inconsistencies in styling of editor content
  src/components/Editor/index.jsx
  src/styles/editor/_editor-content.scss
  src/styles/editor/_table.scss
Labels: patch

#686 Created new axios instance for editor apis
  src/apis/axios.js
  src/apis/direct_uploads.js
  src/apis/emoji_picker.js
  src/apis/unsplash.js
Labels: patch

#685 Fixed conditions for slash commands
  src/components/Editor/index.jsx
Labels: patch

#680 Integrated DynamicVariables from neeto-molecules
  package.json
  src/components/Editor/CustomExtensions/Variable/ExtensionConfig.js
  src/components/Editor/CustomExtensions/Variable/VariableList.jsx
  src/components/Editor/CustomExtensions/Variable/VariableSuggestion.jsx
  src/components/Editor/CustomExtensions/Variable/index.jsx
  src/components/Editor/CustomExtensions/Variable/utils.js
  src/components/Editor/CustomExtensions/hooks/useCustomExtensions.js
  src/components/Editor/Menu/Fixed/index.jsx
  src/components/Editor/index.jsx
  src/components/EditorContent/utils.js
  src/styles/editor/_editor-content.scss
  src/styles/editor/_editor.scss
  src/styles/editor/_menu.scss
  stories/Examples/Variables.stories.mdx
  stories/Examples/constants.js
  yarn.lock
Labels: minor

#690 Added terser plugin to minimise package size.
  dist/codeBlockHighlight.js
  package.json
  rollup.config.js
  yarn.lock
Labels: patch

#692 Replaced Field with FastField
  src/components/Editor/FormikEditor.jsx
Labels: patch

#694 Deleted terser from rollup
  rollup.config.js
Labels: patch

#697 Fixed default props not working
  src/components/Editor/Menu/index.jsx
Labels: patch

#698 Fixed CORS error for image uploads
  dist/codeBlockHighlight.js
  package.json
  src/apis/direct_uploads.js
  src/components/Editor/Menu/index.jsx
Labels: patch

#701 Fixed unsplash response structure and added translations
  src/components/Editor/MediaUploader/UnsplashImagePicker.jsx
  src/translations/en.json
Labels: patch

#705 Removed custom axios instance
  src/apis/axios.js
  src/apis/emoji_picker.js
  src/apis/unsplash.js
  src/components/Editor/MediaUploader/UnsplashImagePicker.jsx
Labels: patch

#715 Fixed copy-pasting image not working
  src/components/Editor/CustomExtensions/Image/ExtensionConfig.js
  src/components/Editor/Menu/Fixed/index.jsx
  src/translations/en.json
Labels: patch

#712 Added option to upload multiple images
  dist/codeBlockHighlight.js
  src/components/Editor/CustomExtensions/Image/ExtensionConfig.js
  src/components/Editor/MediaUploader/LocalUploader.jsx
  src/components/Editor/MediaUploader/MediaEditor.jsx
  src/components/Editor/MediaUploader/Progress.jsx
  src/components/Editor/MediaUploader/URLForm.jsx
  src/components/Editor/MediaUploader/constants.js
  src/components/Editor/MediaUploader/index.jsx
  src/index.scss
  src/styles/components/_attachments.scss
  src/styles/editor/_media-editor.scss
  src/styles/editor/_media-uploader.scss
  src/translations/en.json
Labels: patch

#716 Removed blur command after submitting to keep editor in focus
  src/components/Editor/CustomExtensions/KeyboardShortcuts/ExtensionConfig.js
Labels: patch
