Repository neetozone/neeto-editor, pull requests merged in 2023-02, with the labels that each got.

#593 Connected the neetoUI OverlayManager to neetoEditor focus
  lib/components/Editor/index.jsx
  package.json
  stories/Examples/Editor-with-overlay-manager.stories.mdx
  stories/Examples/EditorWithOverlayManagerDemo.jsx
  yarn.lock
Labels: patch

#597 Added error wrapper for all menu types
  lib/components/Common/ErrorWrapper.jsx
  lib/components/Editor/index.jsx
Labels: patch

#599 Enabled emoji suggestion only right after ":" and a character to enable navigation
  lib/components/Editor/CustomExtensions/Emoji/EmojiSuggestion/EmojiSuggestionMenu.jsx
  lib/components/Editor/CustomExtensions/Emoji/EmojiSuggestion/ExtensionConfig.js
Labels: patch

#598 Added function to check if modals or panes active in editor
  lib/components/Editor/CustomExtensions/Embeds/index.jsx
  lib/components/Editor/utils.js
  lib/index.js
  stories/API-Reference/constants.js
Labels: patch

#601 Updated mentions popup width
  lib/styles/editor/_commands.scss
Labels: patch

#613 Fixed types file
  stories/Examples/Customize-options/Custom-slash-commands.stories.mdx
  types.d.ts
Labels: patch

#616 Added special mention feature
  lib/components/Editor/CustomExtensions/SpecialMentions/ExtensionConfig.js
  lib/components/Editor/CustomExtensions/useCustomExtensions.js
  lib/styles/editor/_editor-content.scss
  stories/Examples/Mentions.stories.mdx
Labels: minor

#618 Removed useOutsideClick hook
  lib/hooks/useOutsideClick.js
Labels: patch

#617 Added feature to limit number of files to be uploaded
  lib/components/Attachments/index.jsx
  lib/components/Attachments/utils.js
Labels: patch

#619 Revamped drop zone ui
  lib/styles/components/_attachments.scss
  stories/constants.js
Labels: patch

#620 Removed unused config prop
  lib/components/Editor/CustomExtensions/constants.js
  lib/components/Editor/CustomExtensions/useCustomExtensions.js
  lib/components/Editor/index.jsx
  stories/API-Reference/constants.js
  types.d.ts
Labels: minor

#621 Added priority for emojis
  lib/components/Editor/CustomExtensions/Emoji/EmojiSuggestion/EmojiSuggestionMenu.jsx
  lib/components/Editor/CustomExtensions/Emoji/EmojiSuggestion/constants.js
  lib/components/Editor/CustomExtensions/Emoji/EmojiSuggestion/utils.js
Labels: patch

#623 Updated eslint rules
  .eslintrc.js
  lib/components/Attachments/Attachment.jsx
  lib/components/Attachments/index.jsx
  lib/components/Editor/CustomExtensions/Emoji/EmojiSuggestion/EmojiSuggestionMenu.jsx
  lib/components/Editor/Menu/Bubble/LinkOption.jsx
  lib/components/Editor/Menu/Fixed/index.jsx
  lib/components/Editor/Menu/Headless/Option/UI/Button.jsx
  lib/components/Editor/Menu/Headless/Option/UI/Dropdown.jsx
  lib/components/Editor/Menu/Headless/constants.js
  lib/components/Editor/Menu/Headless/utils.js
  lib/components/Editor/utils.js
  lib/hooks/useDebounce.js
  lib/hooks/useUppyUploader.js
  lib/utils/constants.js
  lib/utils/scrollhandler.js
Labels: patch

#628 Initial setup for Table extension
  dist/editor-content.min.css
  lib/common/constants.js
  lib/components/Editor/CustomExtensions/SlashCommands/constants.js
  lib/components/Editor/CustomExtensions/Table/ExtensionConfig.js
  lib/components/Editor/CustomExtensions/Table/TableView.js
  lib/components/Editor/CustomExtensions/useCustomExtensions.js
  lib/components/Editor/Menu/Fixed/constants.js
  lib/components/Editor/Menu/Headless/constants.js
  lib/index.scss
  lib/styles/editor/_editor-content.scss
  lib/styles/editor/_table.scss
  package.json
  stories/Examples/Customize-options/Addons.stories.mdx
  yarn.lock
Labels: minor

#630 Added localization for hardcoded strings
  .eslint-rules/neeto.js
  .gitignore
  jsconfig.json
  lib/components/Attachments/Attachment.jsx
  lib/components/Attachments/index.jsx
  lib/components/Attachments/utils.js
  lib/components/Editor/CustomExtensions/Embeds/index.jsx
  lib/components/Editor/MediaUploader/MediaEditor.jsx
  lib/components/Editor/MediaUploader/URLForm.jsx
  lib/components/Editor/Menu/Bubble/Options.jsx
  lib/components/Editor/Menu/Fixed/LinkOption.jsx
  lib/components/Editor/Menu/Fixed/constants.js
  lib/components/Editor/Menu/Fixed/index.jsx
  lib/components/Editor/Menu/Headless/constants.js
  lib/index.js
  lib/translations/en.json
  lib/translations/index.js
  lib/utils/i18next.js
  package.json
  rollup.config.js
  stories/Getting-started.stories.mdx
  yarn.lock
Labels: minor

#641 Added support for children prop in every menu type
  lib/components/Editor/Menu/Bubble/Options.jsx
  lib/components/Editor/Menu/Bubble/index.jsx
  lib/components/Editor/Menu/Fixed/index.jsx
  stories/Examples/constants.js
Labels: patch

#638 Removed `react-i18next `from peerDependencies
  package.json
Labels: patch

#642 Dropdown menu option for table
  lib/components/Editor/Menu/Bubble/Options.jsx
  lib/components/Editor/Menu/Bubble/TableOption.jsx
  lib/components/Editor/Menu/Bubble/index.jsx
  lib/components/Editor/Menu/Fixed/TableOption.jsx
  lib/components/Editor/Menu/Fixed/constants.js
  lib/components/Editor/Menu/Fixed/index.jsx
  lib/styles/editor/_menu.scss
  lib/translations/en.json
Labels: minor

#629 Improved UI for dynamic variables
  lib/components/Editor/CustomExtensions/Variable/VariableList.jsx
  lib/styles/editor/_editor.scss
  lib/styles/editor/_menu.scss
Labels: patch, UI-book

#643 Added app.json and procfile
  Procfile
  app.json
Labels: skip-ci

#650 Serve production build to neeto deploy
  .gitignore
  .storybook/public/.htaccess
  Procfile
  package.json
  yarn.lock
Labels: skip-ci

#648 Added try-catch block to catch errors while adding files to uppy
  lib/components/Attachments/index.jsx
  lib/translations/en.json
Labels: patch

#639 Removed request and response transformations
  src/apis/direct_uploads.js
  src/components/Attachments/Attachment.jsx
  src/components/Attachments/index.jsx
  src/hooks/useUppyUploader.js
  src/utils/DirectUpload/index.js
Labels: patch
