Repository neetozone/neeto-editor, pull requests merged in 2024-07, with the labels that each got.

#1165 Branding changes
  .storybook/neetoLogo.svg
  .storybook/neetoTheme.js
  package.json
  src/styles/editor/menu.scss
  yarn.lock
Labels: patch

#1166 Wraps the defaultMarkInputRule.handler in a try catch block to catch unexpected RangeError.
  src/components/Editor/CustomExtensions/Link/ExtensionConfig.js
Labels: patch

#1167 Fixes the error: flushSync was called from inside a lifecycle method.
  src/components/Editor/CustomExtensions/CodeBlock/CodeBlockComponent.jsx
Labels: patch

#1164 Updates the rollup config to ouput editor styles when the content is used to generate pdf and email.
  dist/editor-output-pdf-email.css
  package.json
  rollup-config/postcss.config.js
  rollup.config.js
  src/styles/editor-output-pdf-email.scss
  yarn.lock
Labels: patch

#1151 Replaces the usages of uppy for uploads with custom hook.
  package.json
  src/components/Attachments/AttachmentProgress.jsx
  src/components/Attachments/constants.js
  src/components/Attachments/index.jsx
  src/components/Attachments/utils.js
  src/components/Editor/MediaUploader/LocalUploader.jsx
  src/components/Editor/MediaUploader/Progress.jsx
  src/components/Editor/MediaUploader/constants.js
  src/hooks/constants/fileUploader.js
  src/hooks/useDropFiles.js
  src/hooks/useFileUploader.js
  src/hooks/useUppyUploader.js
  src/hooks/utils/fileUploader.js
  src/stores/useFileUploadStore.js
  src/styles/components/attachments.scss
  src/styles/editor/_media-uploader.scss
  src/translations/en.json
  src/utils/ActiveStorageUpload.js
  stories/Examples/Customize-options/Image-upload.stories.mdx
  yarn.lock
Labels: patch, beta

#1171 Fixes the variable menu position.
  src/components/Editor/CustomExtensions/Variable/ExtensionConfig.js
  src/styles/editor/menu.scss
Labels: patch

#1169 Added data-cy label to SecondaryMenuTarget
  src/components/Editor/Menu/Fixed/components/EmojiOption.jsx
  src/components/Editor/Menu/Fixed/components/SecondaryMenuTarget.jsx
Labels: patch

#1172 Fixes the empty state UI of the attachment and adds labels to the rows/columns fields in the table menu.
  src/components/Editor/CustomExtensions/Video/VideoComponent.jsx
  src/components/Editor/Menu/Bubble/TableOption.jsx
  src/components/Editor/Menu/Fixed/components/TableOption.jsx
  src/styles/editor/editor-content.scss
  src/styles/editor/menu.scss
  src/translations/en.json
Labels: patch

#1175 Fixed the link color issue
  src/styles/components/attachments.scss
  src/styles/editor/_link-popover.scss
  src/styles/editor/editor-content.scss
Labels: patch

#1178 Improvises the UI of upload progress modal.
  src/components/Attachments/Attachment.jsx
  src/components/Common/FileIcon.jsx
  src/components/Editor/MediaUploader/Progress.jsx
  src/styles/editor/_media-uploader.scss
Labels: patch

#1177 Prevents image and video with empty src being rendered.
  src/components/Editor/CustomExtensions/Image/ImageComponent.jsx
  src/components/Editor/CustomExtensions/Video/VideoComponent.jsx
Labels: patch

#1173 Fixes the editor menu re-rendering for every keystroke.
  package.json
  src/components/Editor/CustomExtensions/Mention/index.jsx
  src/components/Editor/Menu/EmptyMenu.jsx
  src/components/Editor/Menu/Fixed/components/Button.jsx
  src/components/Editor/Menu/Fixed/components/EmojiOption.jsx
  src/components/Editor/Menu/Fixed/components/FontSizeOption.jsx
  src/components/Editor/Menu/Fixed/components/TableOption.jsx
  src/components/Editor/Menu/Fixed/constants.js
  src/components/Editor/Menu/Fixed/hooks/constants.js
  src/components/Editor/Menu/Fixed/hooks/useEditorState.js
  src/components/Editor/Menu/Fixed/index.jsx
  src/components/Editor/Menu/Fixed/utils.js
  src/components/Editor/Menu/Headless/index.jsx
  src/components/Editor/Menu/Headless/utils.js
  src/components/Editor/Menu/constants.js
  src/components/Editor/Menu/index.jsx
  src/components/Editor/index.jsx
  src/stores/useEditorStore.js
Labels: minor

#1180 Fixes padding around the editor mark.
  src/styles/editor/editor-content.scss
Labels: patch

#1179 Creates a playground for neetoEditor in the storybook using the live examples plugin.
  .storybook/main.js
  .storybook/preview.js
  package.json
  stories/API-Reference/All-props.stories.mdx
  stories/API-Reference/Tables.jsx
  stories/API-Reference/constants.js
  stories/Accessibility/Keyboard-shortcuts.stories.mdx
  stories/Examples/Basic.stories.mdx
  stories/Examples/Character-count.stories.mdx
  stories/Examples/Customize-options/Addons.stories.mdx
  stories/Examples/Customize-options/Custom-slash-commands.stories.mdx
  stories/Examples/Customize-options/Image-upload.stories.mdx
  stories/Examples/Customize-options/Override-defaults.stories.mdx
  stories/Examples/Editor-height.stories.mdx
  stories/Examples/Editor-with-overlay-manager.stories.mdx
  stories/Examples/Error-state.stories.mdx
  stories/Examples/Mentions.stories.mdx
  stories/Examples/Menu.stories.mdx
  stories/Examples/Placeholder.stories.mdx
  stories/Examples/Table.stories.mdx
  stories/Examples/Variables.stories.mdx
  stories/Sandbox/Sandbox.mdx
  stories/Sandbox/Sandbox.stories.jsx
  stories/Sandbox/sandbox.scss
  stories/Walkthroughs/Attachments/Attachments.stories.mdx
  stories/Walkthroughs/Attachments/Custom-target.stories.mdx
  stories/Walkthroughs/Attachments/Editor-with-attachments.stories.mdx
  stories/Walkthroughs/Attachments/With-custom-drop-target.stories.mdx
  stories/Walkthroughs/Editor-instance.stories.mdx
  stories/Walkthroughs/Menu-types/BubbleMenu.stories.mdx
  stories/Walkthroughs/Menu-types/FixedMenu.stories.mdx
  stories/Walkthroughs/Menu-types/HeadlessMenu.stories.mdx
  stories/Walkthroughs/Menu-types/SlashCommand.stories.mdx
  yarn.lock
Labels: patch

#1182 Editor table revamp.
  package.json
  src/components/Editor/CustomExtensions/Table/TableActionMenu.jsx
  src/components/Editor/CustomExtensions/Table/utils.js
  src/components/Editor/index.jsx
  src/styles/editor/_table.scss
  yarn.lock
Labels: patch

#1184 Adds missing css variables to the postcss config file.
  dist/editor-output-pdf-email.css
  rollup-config/postcss.config.js
Labels: patch

#1186 Fixes the lag when editing huge articles.
  src/components/Attachments/index.jsx
  src/components/Common/ErrorWrapper.jsx
  src/components/Editor/CustomExtensions/CharacterCount/index.jsx
  src/components/Editor/FormikEditor.jsx
  src/components/Editor/index.jsx
Labels: patch

#1192 Removes the memoization of CharacterCount component.
  src/components/Editor/CustomExtensions/CharacterCount/index.jsx
Labels: patch

#1191 Fixes editing the lists when there are images on top.
  src/components/Editor/CustomExtensions/KeyboardShortcuts/ExtensionConfig.js
Labels: patch

#1190 Fixes the cursor visibility near to the image and the difficulties in adding content between images.
  src/components/Editor/CustomExtensions/Image/ExtensionConfig.js
  src/styles/editor/editor-content.scss
Labels: patch

#1195 Fixes infinite re-render in the fixed menu component.
  src/components/Editor/Menu/Fixed/components/FontSizeOption.jsx
  src/components/Editor/Menu/Fixed/index.jsx
  src/components/Editor/Menu/Fixed/utils.js
Labels: patch

#1196 Fixes the flickering of the drop file UI and overlay stayin permanently when a drop is cancelled.
  src/hooks/useDropFiles.js
Labels: patch
