Repository neetozone/neeto-editor, pull requests merged in 2024-03, with the labels that each got.

#1020 Fixed errors when renaming attachments
  src/components/Attachments/Attachment.jsx
Labels: patch

#1030 Fixed minor bugs and updated stories
  src/components/Editor/CustomExtensions/CodeBlock/CodeBlockComponent.jsx
  src/components/Editor/CustomExtensions/CodeBlock/constants.js
  src/components/EditorContent/constants.js
  src/styles/editor/_editor-content.scss
  src/translations/en.json
  stories/Walkthroughs/Text-formatting.stories.mdx
Labels: patch

#1036 Added GitHub workflow for releasing beta versions
  .github/workflows/publish.yml
Labels: patch

#1038 Added Axios to the peer dependencies
  package.json
  yarn.lock
Labels: patch, beta

#1031 Enhances attachments preview and different document support
  package.json
  src/components/Attachments/Attachment.jsx
  src/components/Attachments/Preview.jsx
  src/components/Attachments/utils.js
  src/styles/components/_attachments.scss
Labels: minor, beta

#1043 Fixed style issues in bubble menu text dropdown
  src/styles/editor/_menu.scss
Labels: patch

#1051 Added data-cy and updated conflicting packages
  package.json
  src/components/Attachments/Attachment.jsx
  src/components/Attachments/Preview.jsx
  src/components/Attachments/constants.js
  src/components/Editor/Menu/Fixed/FontSizeOption.jsx
  yarn.lock
Labels: patch

#1050 Removed auto update PRs workflow
  .github/workflows/auto_update_prs_with_latest_main.yml
Labels: mergepr

#1053 Added a minimum width to the table columns
  src/components/Editor/CustomExtensions/Table/ExtensionConfig.js
Labels: patch

#1054 Sets min-width to the emoji picker container to prevent width changes and placement problems once the content is loaded.
  src/components/Editor/CustomExtensions/Emoji/EmojiPicker/EmojiPickerMenu.jsx
Labels: patch, frontend
