Repository neetozone/neeto-editor, pull requests merged in 2025-06, with the labels that each got.

#1430 Migrated to new module system of SASS
  .storybook/style.scss
  src/index.scss
  src/styles/editor-output-pdf-email.scss
  src/styles/editor-output.scss
  src/styles/editor/_editor.scss
  src/styles/editor/index.scss
Labels: patch

#1434 Calculated a safe position to insert the paragraph tag to prevent overflow
  src/components/Editor/MediaUploader/index.jsx
Labels: patch

#1436 Prevent highlight of lines when the line number to be highlighted is more than the number of lines
  src/components/EditorContent/utils/index.js
Labels: patch

#1437 Bump version
  package.json
Labels: mergepr

#1444 Use the id to calculate the position of the empty image node during upload failures
  src/components/Editor/CustomExtensions/Image/ExtensionConfig.js
Labels: patch

#1446 Added callout extension to editor
  src/common/constants.js
  src/components/Editor/CustomExtensions/Callout/CalloutComponent.jsx
  src/components/Editor/CustomExtensions/Callout/ExtensionConfig.js
  src/components/Editor/CustomExtensions/hooks/useCustomExtensions.js
  src/components/Editor/Menu/Fixed/components/CalloutDropdown/CalloutIcon.jsx
  src/components/Editor/Menu/Fixed/components/CalloutDropdown/CalloutTypeOption.jsx
  src/components/Editor/Menu/Fixed/components/CalloutDropdown/RenderCalloutOptions.jsx
  src/components/Editor/Menu/Fixed/components/CalloutDropdown/constants.js
  src/components/Editor/Menu/Fixed/components/CalloutDropdown/index.jsx
  src/components/Editor/Menu/Fixed/constants.js
  src/components/Editor/Menu/Fixed/hooks/constants.js
  src/components/Editor/Menu/Fixed/utils.js
  src/styles/editor/_callout.scss
  src/styles/editor/index.scss
  src/translations/en.json
  stories/Examples/Customize-options/Addons.stories.mdx
  stories/constants.js
Labels: patch

#1450 Bump version
  package.json
Labels: mergepr

#1454 Removed unnecessary slash from regex
  src/components/EditorContent/utils/index.js
Labels: patch

#1455 Bump version
  package.json
Labels: mergepr

#1451 Added additional options for slash commands
  src/components/Editor/CustomExtensions/SlashCommands/ExtensionConfig.js
  src/components/Editor/CustomExtensions/SlashCommands/Menu.jsx
  src/components/Editor/CustomExtensions/SlashCommands/constants.js
  src/components/Editor/CustomExtensions/SlashCommands/utils.js
  src/components/Editor/CustomExtensions/hooks/useCustomExtensions.js
  src/components/Editor/index.jsx
  src/translations/en.json
Labels: patch

#1456 Set hideSlashCommands to true by default in Editor component
  src/components/Editor/index.jsx
Labels: patch

#1458 Bump version
  package.json
Labels: mergepr

#1460 Improve the UI for Todo-list extension
  src/styles/editor/_todo-list.scss
Labels: patch

#1467 Bump version
  package.json
Labels: mergepr

#1470 Bump version
  package.json
Labels: mergepr

#1475 Test release
  .scripts/bump_version.sh
Labels: patch, instant-mergepr

#1478 Revert "migrated to new module system of SASS (#1430)"
  .storybook/style.scss
  src/index.scss
  src/styles/editor/_editor.scss
  src/styles/editor/index.scss
Labels: patch

#1474 Bump version
  package.json
Labels: mergepr

#1481 Adds ability to pass down attachment props
  src/components/Editor/index.jsx
Labels: patch

#1483 Test release
  README.md
Labels: patch

#1485 Test release
  README.md
Labels: patch

#1486 Test release
  README.md
Labels: patch
