Repository neetozone/neeto-editor, pull requests merged in 2025-05, with the labels that each got.

#1377 Updated header links to GitHub style tag links
  src/components/EditorContent/utils/headers.js
  src/styles/editor/editor-content.scss
Labels: patch

#1378 Fixed CDN upload after every publish
  package.json
  src/styles/editor/editor-content.scss
Labels: patch

#1380 New version release
  .github/workflows/create_and_publish_releases.yml
  .github/workflows/publish.yml
Labels: patch

#1386 Add Highlight dropdown UI
  src/components/Editor/Menu/Fixed/HighlightDropdown.jsx
  src/components/Editor/Menu/Fixed/index.jsx
  src/styles/editor/_highlight.scss
  src/styles/editor/editor-content.scss
  src/styles/editor/index.scss
Labels: patch

#1387 Bump version
  package.json
Labels: mergepr

#1389 Ensure addonCommands is applicable for both slash commands and menu
  src/components/Editor/CustomExtensions/SlashCommands/utils.js
  stories/Examples/Customize-options/Custom-slash-commands.stories.mdx
  types.d.ts
Labels: minor

#1390 Bump version
  package.json
Labels: mergepr

#1388 Update Header dropdown UI
  package.json
  src/components/Editor/Menu/Fixed/components/FontSizeOption.jsx
  src/components/Editor/Menu/constants.js
  src/styles/editor/menu.scss
  yarn.lock
Labels: patch

#1395 Fixed secondary dropdown emoji issue
  src/components/Editor/Menu/Fixed/components/EmojiOption.jsx
Labels: patch

#1396 Bump version
  package.json
Labels: mergepr

#1400 Revamped the editor toolbar
  src/components/Editor/Menu/Fixed/components/Button.jsx
  src/components/Editor/Menu/Fixed/constants.js
  src/components/Editor/Menu/Fixed/utils.js
  src/translations/en.json
Labels: minor

#1402 Added HighlightDropdown component and integrated it into the menu options
  src/components/Editor/CustomExtensions/hooks/useCustomExtensions.js
  src/components/Editor/Menu/Fixed/HighlightDropdown.jsx
  src/components/Editor/Menu/Fixed/components/HighlightDropdown/ColorDot.jsx
  src/components/Editor/Menu/Fixed/components/HighlightDropdown/constants.js
  src/components/Editor/Menu/Fixed/components/HighlightDropdown/index.jsx
  src/components/Editor/Menu/Fixed/constants.js
  src/components/Editor/Menu/Fixed/index.jsx
  src/components/Editor/Menu/Fixed/utils.js
Labels: minor

#1403 Bump version
  package.json
Labels: mergepr

#1408 Improve Bubble menu styles
  src/components/Editor/Menu/Bubble/Options.jsx
  src/components/Editor/Menu/Bubble/TableOption.jsx
  src/components/Editor/Menu/Bubble/index.jsx
  src/components/Editor/Menu/Bubble/utils.jsx
  src/components/Editor/Menu/Fixed/components/TextColorOption.jsx
  src/styles/editor/menu.scss
Labels: patch

#1409 Bump version
  package.json
Labels: mergepr

#1413 Bump version
  package.json
Labels: mergepr

#1415 Set the proper key to the Slash menu items to prevent incorrect renders
  src/components/Editor/CustomExtensions/SlashCommands/Menu.jsx
  src/translations/en.json
Labels: patch

#1416 Bump version
  package.json
Labels: mergepr

#1427 Bump version
  package.json
Labels: mergepr
